include: package:flutter_lints/flutter.yaml
formatter:
  trailing_commas: preserve
analyzer:
  exclude:
    - bricks/**
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    unnecessary_null_checks: true
    prefer_final_locals: true
    always_declare_return_types: true


# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.
